# Generated by Django 4.2.3 on 2023-10-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_registerdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='workdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now=True)),
                ('Customer', models.CharField(blank=True, max_length=50, null=True)),
                ('Mobile', models.IntegerField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=50, null=True)),
                ('Content', models.CharField(blank=True, max_length=50, null=True)),
                ('ContentImage', models.ImageField(blank=True, null=True, upload_to='works')),
                ('Service', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
