# Generated by Django 4.2.3 on 2023-10-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_workdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdb',
            name='Amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workdb',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
